### ISSUE TITLE
Error generated when addin cancelled

### ISSUE THREAD

**Issue by TThurlow** [lbusett/insert_table#1]
Version 0.0.3

An error is generated when the 'Cancel' button is pressed rather than 'Done' from the addin.

Error in if (out_format == "kable") { : argument is of length zero

The "kable" statement is always present, even if another format is chosen first.

**Comment by lbusett** [comment]
Thanks for signaling this. Will fix ity ASAP.

**Comment by lbusett** [comment]
should be fixed now. Thanks.
